# Generated by Django 3.2.7 on 2021-09-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='username',
            field=models.CharField(default='init', max_length=20),
            preserve_default=False,
        ),
    ]
