# Generated by Django 3.2.7 on 2021-09-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_token_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='token',
            new_name='user',
        ),
    ]
