# Generated by Django 3.2.7 on 2021-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
